Repository Vladdd97/Airline-Tickets-System, pull requests merged in 2021-02, with the labels that each got.

#4 #3: add swagger to project
  pom.xml
  src/main/java/com/airiline/tickets/configuration/SwaggerConfiguration.java
Labels: feature

#14 ATS-12: add swagger to project
  pom.xml
  src/main/java/com/airiline/tickets/configuration/SwaggerConfiguration.java
Labels: feature

#15 Ats 11 add tickets crud operations
  pom.xml
  src/main/java/com/airiline/tickets/controller/TicketController.java
  src/main/java/com/airiline/tickets/domain/AbstractEntity.java
  src/main/java/com/airiline/tickets/domain/Ticket.java
  src/main/java/com/airiline/tickets/dto/CreateTicketRequest.java
  src/main/java/com/airiline/tickets/dto/CreateTicketResponse.java
  src/main/java/com/airiline/tickets/dto/TicketResponse.java
  src/main/java/com/airiline/tickets/dto/UpdateTicketRequest.java
  src/main/java/com/airiline/tickets/mapper/TicketMapper.java
  src/main/java/com/airiline/tickets/repository/TicketRepository.java
  src/main/java/com/airiline/tickets/service/TicketService.java
  src/main/java/com/airiline/tickets/service/impl/TicketServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/airiline/tickets/TicketApplicationTests.java
Labels: feature

#22 ATS-16: add create flight endpoint
  src/main/java/com/airiline/tickets/controller/FlightController.java
  src/main/java/com/airiline/tickets/domain/Flight.java
  src/main/java/com/airiline/tickets/dto/flight/CreateFlightRequest.java
  src/main/java/com/airiline/tickets/dto/flight/CreateFlightResponse.java
  src/main/java/com/airiline/tickets/mapper/FlightMapper.java
  src/main/java/com/airiline/tickets/repository/FlightRepository.java
  src/main/java/com/airiline/tickets/service/FlightService.java
  src/main/java/com/airiline/tickets/service/impl/FlightServiceImpl.java
Labels: feature

#24 ATS-23: added integration testing base
  pom.xml
  src/test/java/com/airiline/tickets/TicketApplicationTests.java
  src/test/java/com/airiline/tickets/controller/BaseControllerIT.java
  src/test/java/com/airiline/tickets/controller/TicketControllerIT.java
  src/test/resources/application-test-db.yml
  src/test/resources/expected-response/create-ticket-response-success.json
  src/test/resources/expected-response/get-ticket-by-id-not-found-error.json
  src/test/resources/expected-response/get-ticket-by-id-success.json
  src/test/resources/mock-request/create-ticket-request-success.json
  src/test/resources/sql/insertTicket_101.sql
Labels: feature, improvement

#25 ATS-17: add get flight by id endpoint
  src/main/java/com/airiline/tickets/controller/FlightController.java
  src/main/java/com/airiline/tickets/dto/flight/FlightResponse.java
  src/main/java/com/airiline/tickets/mapper/FlightMapper.java
  src/main/java/com/airiline/tickets/service/FlightService.java
  src/main/java/com/airiline/tickets/service/impl/FlightServiceImpl.java
Labels: feature

#26 ATS-18: add delete flight endpoint
  src/main/java/com/airiline/tickets/controller/FlightController.java
  src/main/java/com/airiline/tickets/service/FlightService.java
  src/main/java/com/airiline/tickets/service/impl/FlightServiceImpl.java
Labels: feature

#30 ATS-29: handle entity not found exceptions on deleting request
  src/main/java/com/airiline/tickets/service/impl/FlightServiceImpl.java
  src/main/java/com/airiline/tickets/service/impl/TicketServiceImpl.java
Labels: improvement
